# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5764244850681dd8dc5c2fd7a3586927fabf0dadf2bb6b3fbd9d4b9548b2c5dcef6b03c7b295855c086af30dd0b6697ea7a3cd313cb58c8e07c72b1c12198e1b

test:
  secret_key_base: b1f5c3305ce9ac2f6271384b15e61844ea9988ce1e4f98a0019644e6c787808c06ac3ebbd90845ec25cdf2ace5efd617eb6dac12ecd6f7ec9186e781c7ddd377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
